const { PrismaClient } = require("@prisma/client");
const {
  ConfigCategory,
  ConfigStatus,
  FeatureLevel,
  VehicleGrade,
} = require("../src/utils/constants");

const prisma = new PrismaClient();

const configItems = [
  {
    name: "毫米波雷达",
    category: ConfigCategory.PERCEPTION,
    typicalWeight: 2.5,
    featureLevel: FeatureLevel.STANDARD,
    status: ConfigStatus.ACTIVE,
    description: "77GHz毫米波雷达，用于自适应巡航和自动紧急制动",
    popularityRate: 0.85,
    isHighlyAdopted: true,
    versionGroupId: "RADAR_MMWAVE",
    versionCode: "V3",
    versionOrder: 3,
    isLatestVersion: true,
    releaseYear: 2023,
    weightSavingFromPrev: 0.8,
  },
  {
    name: "前向摄像头",
    category: ConfigCategory.PERCEPTION,
    typicalWeight: 0.3,
    featureLevel: FeatureLevel.BASIC,
    status: ConfigStatus.ACTIVE,
    description: "单目摄像头，用于车道保持和交通标志识别",
    popularityRate: 0.92,
    isHighlyAdopted: true,
    versionGroupId: "CAMERA_FRONT",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2022,
    weightSavingFromPrev: 0.1,
  },
  {
    name: "环视摄像头",
    category: ConfigCategory.PERCEPTION,
    typicalWeight: 0.8,
    featureLevel: FeatureLevel.STANDARD,
    status: ConfigStatus.ACTIVE,
    description: "4颗鱼眼摄像头组成360°全景影像系统",
    popularityRate: 0.78,
    isHighlyAdopted: true,
    versionGroupId: "CAMERA_SURROUND",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2023,
    weightSavingFromPrev: 0.4,
  },
  {
    name: "超声波雷达",
    category: ConfigCategory.PERCEPTION,
    typicalWeight: 1.2,
    featureLevel: FeatureLevel.BASIC,
    status: ConfigStatus.ACTIVE,
    description: "12颗超声波雷达，用于自动泊车和近距离测距",
    popularityRate: 0.95,
    isHighlyAdopted: true,
    versionGroupId: "RADAR_ULTRASONIC",
    versionCode: "V3",
    versionOrder: 3,
    isLatestVersion: true,
    releaseYear: 2022,
    weightSavingFromPrev: 0.3,
  },
  {
    name: "激光雷达",
    category: ConfigCategory.PERCEPTION,
    typicalWeight: 6.5,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.NEW,
    description: "混合固态激光雷达，探测距离200m",
    popularityRate: 0.25,
    isHighlyAdopted: false,
    versionGroupId: "RADAR_LIDAR",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2024,
    weightSavingFromPrev: 2.5,
  },
  {
    name: "侧方雷达",
    category: ConfigCategory.PERCEPTION,
    typicalWeight: 1.8,
    featureLevel: FeatureLevel.STANDARD,
    status: ConfigStatus.ACTIVE,
    description: "24GHz毫米波雷达，用于盲点监测和变道辅助",
    popularityRate: 0.72,
    isHighlyAdopted: true,
    versionGroupId: "RADAR_SIDE",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2022,
    weightSavingFromPrev: 0.5,
  },
  {
    name: "车内摄像头",
    category: ConfigCategory.PERCEPTION,
    typicalWeight: 0.15,
    featureLevel: FeatureLevel.ADVANCED,
    status: ConfigStatus.ACTIVE,
    description: "驾驶员状态监测摄像头",
    popularityRate: 0.45,
    isHighlyAdopted: false,
  },
  {
    name: "高精定位模块",
    category: ConfigCategory.PERCEPTION,
    typicalWeight: 0.4,
    featureLevel: FeatureLevel.ADVANCED,
    status: ConfigStatus.NEW,
    description: "GNSS+IMU组合导航，厘米级定位",
    popularityRate: 0.38,
    isHighlyAdopted: false,
  },

  {
    name: "智驾域控制器",
    category: ConfigCategory.COMPUTING,
    typicalWeight: 3.5,
    featureLevel: FeatureLevel.ADVANCED,
    status: ConfigStatus.ACTIVE,
    description: "单Orin-X芯片，200TOPS算力",
    popularityRate: 0.55,
    isHighlyAdopted: true,
    versionGroupId: "DCU_ADAS",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2023,
    weightSavingFromPrev: 1.2,
  },
  {
    name: "高端智驾域控制器",
    category: ConfigCategory.COMPUTING,
    typicalWeight: 5.2,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.NEW,
    description: "双Orin-X芯片，508TOPS算力，支持城市NOA",
    popularityRate: 0.22,
    isHighlyAdopted: false,
    versionGroupId: "DCU_ADAS_HIGH",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2024,
    weightSavingFromPrev: 1.8,
  },
  {
    name: "座舱域控制器",
    category: ConfigCategory.COMPUTING,
    typicalWeight: 2.8,
    featureLevel: FeatureLevel.STANDARD,
    status: ConfigStatus.ACTIVE,
    description: "高通8155芯片，多屏互动",
    popularityRate: 0.68,
    isHighlyAdopted: true,
    versionGroupId: "DCU_COCKPIT",
    versionCode: "V3",
    versionOrder: 3,
    isLatestVersion: true,
    releaseYear: 2023,
    weightSavingFromPrev: 0.7,
  },
  {
    name: "高端座舱域控制器",
    category: ConfigCategory.COMPUTING,
    typicalWeight: 4.5,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.NEW,
    description: "高通8295芯片，AI大模型算力",
    popularityRate: 0.18,
    isHighlyAdopted: false,
    versionGroupId: "DCU_COCKPIT_HIGH",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2024,
    weightSavingFromPrev: 1.0,
  },
  {
    name: "整车域控制器",
    category: ConfigCategory.COMPUTING,
    typicalWeight: 1.5,
    featureLevel: FeatureLevel.ADVANCED,
    status: ConfigStatus.ACTIVE,
    description: "中央计算平台，整车电子电气架构核心",
    popularityRate: 0.42,
    isHighlyAdopted: false,
  },
  {
    name: "泊车域控制器",
    category: ConfigCategory.COMPUTING,
    typicalWeight: 1.2,
    featureLevel: FeatureLevel.STANDARD,
    status: ConfigStatus.OBSOLETE,
    description: "独立泊车控制单元，将被整合进智驾域",
    popularityRate: 0.35,
    isHighlyAdopted: false,
  },
  {
    name: "电源管理单元",
    category: ConfigCategory.COMPUTING,
    typicalWeight: 2.0,
    featureLevel: FeatureLevel.STANDARD,
    status: ConfigStatus.ACTIVE,
    description: "智能电源分配和管理系统",
    popularityRate: 0.88,
    isHighlyAdopted: true,
  },

  {
    name: "5G通信模块",
    category: ConfigCategory.COMMUNICATION,
    typicalWeight: 0.6,
    featureLevel: FeatureLevel.ADVANCED,
    status: ConfigStatus.ACTIVE,
    description: "5G+C-V2X双模通信模块",
    popularityRate: 0.48,
    isHighlyAdopted: true,
    versionGroupId: "COMM_5G",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2023,
    weightSavingFromPrev: 0.3,
  },
  {
    name: "4G通信模块",
    category: ConfigCategory.COMMUNICATION,
    typicalWeight: 0.4,
    featureLevel: FeatureLevel.BASIC,
    status: ConfigStatus.ACTIVE,
    description: "4G LTE通信模块",
    popularityRate: 0.82,
    isHighlyAdopted: true,
  },
  {
    name: "V2X车路协同模块",
    category: ConfigCategory.COMMUNICATION,
    typicalWeight: 0.8,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.NEW,
    description: "PC5直连通信，支持车车、车路交互",
    popularityRate: 0.15,
    isHighlyAdopted: false,
  },
  {
    name: "蓝牙模块",
    category: ConfigCategory.COMMUNICATION,
    typicalWeight: 0.05,
    featureLevel: FeatureLevel.BASIC,
    status: ConfigStatus.ACTIVE,
    description: "蓝牙5.2，支持手机钥匙",
    popularityRate: 0.98,
    isHighlyAdopted: true,
    versionGroupId: "COMM_BT",
    versionCode: "V4",
    versionOrder: 4,
    isLatestVersion: true,
    releaseYear: 2022,
    weightSavingFromPrev: 0.02,
  },
  {
    name: "WiFi模块",
    category: ConfigCategory.COMMUNICATION,
    typicalWeight: 0.08,
    featureLevel: FeatureLevel.BASIC,
    status: ConfigStatus.ACTIVE,
    description: "WiFi 6，支持车内热点",
    popularityRate: 0.75,
    isHighlyAdopted: true,
    versionGroupId: "COMM_WIFI",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2021,
    weightSavingFromPrev: 0.04,
  },
  {
    name: "卫星通信模块",
    category: ConfigCategory.COMMUNICATION,
    typicalWeight: 1.2,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.NEW,
    description: "北斗短报文/天通卫星通信",
    popularityRate: 0.08,
    isHighlyAdopted: false,
  },
  {
    name: "UWB模块",
    category: ConfigCategory.COMMUNICATION,
    typicalWeight: 0.15,
    featureLevel: FeatureLevel.ADVANCED,
    status: ConfigStatus.NEW,
    description: "超宽带通信，厘米级测距",
    popularityRate: 0.12,
    isHighlyAdopted: false,
  },
  {
    name: "DSRC模块",
    category: ConfigCategory.COMMUNICATION,
    typicalWeight: 0.5,
    featureLevel: FeatureLevel.ADVANCED,
    status: ConfigStatus.OBSOLETE,
    description: "专用短程通信，已被C-V2X替代",
    popularityRate: 0.05,
    isHighlyAdopted: false,
  },

  {
    name: "线控制动系统",
    category: ConfigCategory.ACTUATION,
    typicalWeight: 4.5,
    featureLevel: FeatureLevel.STANDARD,
    status: ConfigStatus.ACTIVE,
    description: "电子液压制动，支持能量回收",
    popularityRate: 0.65,
    isHighlyAdopted: true,
    versionGroupId: "BRAKE_BY_WIRE",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2023,
    weightSavingFromPrev: 1.5,
  },
  {
    name: "线控转向系统",
    category: ConfigCategory.ACTUATION,
    typicalWeight: 3.8,
    featureLevel: FeatureLevel.ADVANCED,
    status: ConfigStatus.ACTIVE,
    description: "冗余设计，支持L3+自动驾驶",
    popularityRate: 0.28,
    isHighlyAdopted: false,
    versionGroupId: "STEER_BY_WIRE",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2024,
    weightSavingFromPrev: 1.2,
  },
  {
    name: "电子稳定系统",
    category: ConfigCategory.ACTUATION,
    typicalWeight: 2.2,
    featureLevel: FeatureLevel.BASIC,
    status: ConfigStatus.ACTIVE,
    description: "ESP 9.3，车身电子稳定系统",
    popularityRate: 0.96,
    isHighlyAdopted: true,
    versionGroupId: "ESP",
    versionCode: "V4",
    versionOrder: 4,
    isLatestVersion: true,
    releaseYear: 2021,
    weightSavingFromPrev: 0.6,
  },
  {
    name: "电动助力转向",
    category: ConfigCategory.ACTUATION,
    typicalWeight: 3.2,
    featureLevel: FeatureLevel.BASIC,
    status: ConfigStatus.ACTIVE,
    description: "EPS电动助力转向系统",
    popularityRate: 0.94,
    isHighlyAdopted: true,
    versionGroupId: "EPS",
    versionCode: "V3",
    versionOrder: 3,
    isLatestVersion: true,
    releaseYear: 2022,
    weightSavingFromPrev: 0.8,
  },
  {
    name: "空气悬架系统",
    category: ConfigCategory.ACTUATION,
    typicalWeight: 12.5,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.ACTIVE,
    description: "主动空气悬架，可调节车身高度",
    popularityRate: 0.18,
    isHighlyAdopted: false,
  },
  {
    name: "后轮转向系统",
    category: ConfigCategory.ACTUATION,
    typicalWeight: 5.8,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.ACTIVE,
    description: "后轮随动转向，最大转向角5°",
    popularityRate: 0.12,
    isHighlyAdopted: false,
  },
  {
    name: "主动防倾杆",
    category: ConfigCategory.ACTUATION,
    typicalWeight: 4.2,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.ACTIVE,
    description: "电子稳定杆，抑制侧倾",
    popularityRate: 0.08,
    isHighlyAdopted: false,
  },

  {
    name: "中控大屏",
    category: ConfigCategory.DISPLAY,
    typicalWeight: 1.8,
    featureLevel: FeatureLevel.STANDARD,
    status: ConfigStatus.ACTIVE,
    description: "15.6英寸中控触控屏",
    popularityRate: 0.85,
    isHighlyAdopted: true,
    versionGroupId: "DISPLAY_CENTER",
    versionCode: "V3",
    versionOrder: 3,
    isLatestVersion: true,
    releaseYear: 2023,
    weightSavingFromPrev: 0.5,
  },
  {
    name: "全液晶仪表",
    category: ConfigCategory.DISPLAY,
    typicalWeight: 1.2,
    featureLevel: FeatureLevel.STANDARD,
    status: ConfigStatus.ACTIVE,
    description: "12.3英寸全液晶仪表盘",
    popularityRate: 0.78,
    isHighlyAdopted: true,
    versionGroupId: "DISPLAY_CLUSTER",
    versionCode: "V2",
    versionOrder: 2,
    isLatestVersion: true,
    releaseYear: 2022,
    weightSavingFromPrev: 0.4,
  },
  {
    name: "HUD抬头显示",
    category: ConfigCategory.DISPLAY,
    typicalWeight: 1.5,
    featureLevel: FeatureLevel.ADVANCED,
    status: ConfigStatus.ACTIVE,
    description: "AR-HUD增强现实抬头显示",
    popularityRate: 0.35,
    isHighlyAdopted: false,
  },
  {
    name: "副驾娱乐屏",
    category: ConfigCategory.DISPLAY,
    typicalWeight: 1.3,
    featureLevel: FeatureLevel.ADVANCED,
    status: ConfigStatus.ACTIVE,
    description: "12.3英寸副驾专属娱乐屏",
    popularityRate: 0.25,
    isHighlyAdopted: false,
  },
  {
    name: "后排娱乐屏",
    category: ConfigCategory.DISPLAY,
    typicalWeight: 2.8,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.ACTIVE,
    description: "双11.6英寸后排头枕屏",
    popularityRate: 0.15,
    isHighlyAdopted: false,
  },
  {
    name: "电子外后视镜",
    category: ConfigCategory.DISPLAY,
    typicalWeight: 1.6,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.NEW,
    description: "电子后视镜+车内显示屏",
    popularityRate: 0.05,
    isHighlyAdopted: false,
  },
  {
    name: "星空顶天幕",
    category: ConfigCategory.DISPLAY,
    typicalWeight: 8.5,
    featureLevel: FeatureLevel.PREMIUM,
    status: ConfigStatus.ACTIVE,
    description: "可变色全景天幕，带星空效果",
    popularityRate: 0.12,
    isHighlyAdopted: false,
  },
  {
    name: "智能氛围灯",
    category: ConfigCategory.DISPLAY,
    typicalWeight: 0.5,
    featureLevel: FeatureLevel.BASIC,
    status: ConfigStatus.ACTIVE,
    description: "256色车内氛围灯，可随音乐律动",
    popularityRate: 0.68,
    isHighlyAdopted: true,
  },
];

const configItemVersions = [
  {
    versionGroupId: "RADAR_MMWAVE",
    versionCode: "V1",
    versionName: "第一代毫米波雷达",
    versionOrder: 1,
    weight: 4.0,
    weightSaving: 0,
    releaseYear: 2018,
    isCurrent: false,
    description: "早期24GHz毫米波雷达",
    improvementNotes: "基础ACC功能",
  },
  {
    versionGroupId: "RADAR_MMWAVE",
    versionCode: "V2",
    versionName: "第二代毫米波雷达",
    versionOrder: 2,
    weight: 3.3,
    weightSaving: 0.7,
    releaseYear: 2020,
    isCurrent: false,
    description: "77GHz毫米波雷达，增加AEB功能",
    improvementNotes: "频率提升，探测距离增加",
  },
  {
    versionGroupId: "RADAR_MMWAVE",
    versionCode: "V3",
    versionName: "第三代毫米波雷达",
    versionOrder: 3,
    weight: 2.5,
    weightSaving: 0.8,
    releaseYear: 2023,
    isCurrent: true,
    description: "77GHz毫米波雷达，支持角雷达一体化",
    improvementNotes: "集成度提升，重量大幅降低",
  },
  {
    versionGroupId: "CAMERA_FRONT",
    versionCode: "V1",
    versionName: "第一代前向摄像头",
    versionOrder: 1,
    weight: 0.4,
    weightSaving: 0,
    releaseYear: 2019,
    isCurrent: false,
    description: "单目摄像头，基础LKA功能",
    improvementNotes: "基础驾驶辅助",
  },
  {
    versionGroupId: "CAMERA_FRONT",
    versionCode: "V2",
    versionName: "第二代前向摄像头",
    versionOrder: 2,
    weight: 0.3,
    weightSaving: 0.1,
    releaseYear: 2022,
    isCurrent: true,
    description: "8MP高清单目摄像头，支持交通标志识别",
    improvementNotes: "分辨率提升，算法优化",
  },
  {
    versionGroupId: "CAMERA_SURROUND",
    versionCode: "V1",
    versionName: "第一代环视摄像头",
    versionOrder: 1,
    weight: 1.2,
    weightSaving: 0,
    releaseYear: 2020,
    isCurrent: false,
    description: "4颗摄像头组成全景影像",
    improvementNotes: "基础360°影像",
  },
  {
    versionGroupId: "CAMERA_SURROUND",
    versionCode: "V2",
    versionName: "第二代环视摄像头",
    versionOrder: 2,
    weight: 0.8,
    weightSaving: 0.4,
    releaseYear: 2023,
    isCurrent: true,
    description: "4颗2MP鱼眼摄像头，支持自动泊车",
    improvementNotes: "摄像头集成度提升，线束优化",
  },
  {
    versionGroupId: "RADAR_ULTRASONIC",
    versionCode: "V1",
    versionName: "第一代超声波雷达",
    versionOrder: 1,
    weight: 1.8,
    weightSaving: 0,
    releaseYear: 2017,
    isCurrent: false,
    description: "8颗超声波雷达",
    improvementNotes: "基础泊车辅助",
  },
  {
    versionGroupId: "RADAR_ULTRASONIC",
    versionCode: "V2",
    versionName: "第二代超声波雷达",
    versionOrder: 2,
    weight: 1.5,
    weightSaving: 0.3,
    releaseYear: 2019,
    isCurrent: false,
    description: "12颗超声波雷达，增加侧向探测",
    improvementNotes: "探测范围扩大",
  },
  {
    versionGroupId: "RADAR_ULTRASONIC",
    versionCode: "V3",
    versionName: "第三代超声波雷达",
    versionOrder: 3,
    weight: 1.2,
    weightSaving: 0.3,
    releaseYear: 2022,
    isCurrent: true,
    description: "12颗数字超声波雷达，支持自动泊车",
    improvementNotes: "数字化，功耗降低",
  },
  {
    versionGroupId: "RADAR_LIDAR",
    versionCode: "V1",
    versionName: "第一代激光雷达",
    versionOrder: 1,
    weight: 9.0,
    weightSaving: 0,
    releaseYear: 2021,
    isCurrent: false,
    description: "机械旋转激光雷达",
    improvementNotes: "早期自动驾驶方案",
  },
  {
    versionGroupId: "RADAR_LIDAR",
    versionCode: "V2",
    versionName: "第二代激光雷达",
    versionOrder: 2,
    weight: 6.5,
    weightSaving: 2.5,
    releaseYear: 2024,
    isCurrent: true,
    description: "混合固态激光雷达",
    improvementNotes: "固态化，重量大幅降低",
  },
  {
    versionGroupId: "RADAR_SIDE",
    versionCode: "V1",
    versionName: "第一代侧方雷达",
    versionOrder: 1,
    weight: 2.3,
    weightSaving: 0,
    releaseYear: 2019,
    isCurrent: false,
    description: "24GHz雷达，盲点监测",
    improvementNotes: "基础BSD功能",
  },
  {
    versionGroupId: "RADAR_SIDE",
    versionCode: "V2",
    versionName: "第二代侧方雷达",
    versionOrder: 2,
    weight: 1.8,
    weightSaving: 0.5,
    releaseYear: 2022,
    isCurrent: true,
    description: "24GHz雷达，支持变道辅助",
    improvementNotes: "集成度提升",
  },
  {
    versionGroupId: "DCU_ADAS",
    versionCode: "V1",
    versionName: "第一代智驾域控制器",
    versionOrder: 1,
    weight: 4.7,
    weightSaving: 0,
    releaseYear: 2021,
    isCurrent: false,
    description: "单Orin-X芯片，100TOPS",
    improvementNotes: "早期智驾域方案",
  },
  {
    versionGroupId: "DCU_ADAS",
    versionCode: "V2",
    versionName: "第二代智驾域控制器",
    versionOrder: 2,
    weight: 3.5,
    weightSaving: 1.2,
    releaseYear: 2023,
    isCurrent: true,
    description: "单Orin-X芯片，200TOPS算力",
    improvementNotes: "算力提升，集成度优化",
  },
  {
    versionGroupId: "DCU_ADAS_HIGH",
    versionCode: "V1",
    versionName: "第一代高端智驾域控制器",
    versionOrder: 1,
    weight: 7.0,
    weightSaving: 0,
    releaseYear: 2022,
    isCurrent: false,
    description: "双Orin-X芯片",
    improvementNotes: "早期高阶智驾方案",
  },
  {
    versionGroupId: "DCU_ADAS_HIGH",
    versionCode: "V2",
    versionName: "第二代高端智驾域控制器",
    versionOrder: 2,
    weight: 5.2,
    weightSaving: 1.8,
    releaseYear: 2024,
    isCurrent: true,
    description: "双Orin-X芯片，508TOPS算力",
    improvementNotes: "算力提升，热管理优化",
  },
  {
    versionGroupId: "DCU_COCKPIT",
    versionCode: "V1",
    versionName: "第一代座舱域控制器",
    versionOrder: 1,
    weight: 4.0,
    weightSaving: 0,
    releaseYear: 2020,
    isCurrent: false,
    description: "高通820A芯片",
    improvementNotes: "早期座舱域方案",
  },
  {
    versionGroupId: "DCU_COCKPIT",
    versionCode: "V2",
    versionName: "第二代座舱域控制器",
    versionOrder: 2,
    weight: 3.5,
    weightSaving: 0.5,
    releaseYear: 2021,
    isCurrent: false,
    description: "高通8155芯片",
    improvementNotes: "性能提升",
  },
  {
    versionGroupId: "DCU_COCKPIT",
    versionCode: "V3",
    versionName: "第三代座舱域控制器",
    versionOrder: 3,
    weight: 2.8,
    weightSaving: 0.7,
    releaseYear: 2023,
    isCurrent: true,
    description: "高通8155芯片，多屏互动",
    improvementNotes: "集成度提升，重量降低",
  },
  {
    versionGroupId: "DCU_COCKPIT_HIGH",
    versionCode: "V1",
    versionName: "第一代高端座舱域控制器",
    versionOrder: 1,
    weight: 5.5,
    weightSaving: 0,
    releaseYear: 2023,
    isCurrent: false,
    description: "高通8295工程样件",
    improvementNotes: "早期大模型算力方案",
  },
  {
    versionGroupId: "DCU_COCKPIT_HIGH",
    versionCode: "V2",
    versionName: "第二代高端座舱域控制器",
    versionOrder: 2,
    weight: 4.5,
    weightSaving: 1.0,
    releaseYear: 2024,
    isCurrent: true,
    description: "高通8295芯片，AI大模型算力",
    improvementNotes: "量产优化，重量降低",
  },
  {
    versionGroupId: "COMM_5G",
    versionCode: "V1",
    versionName: "第一代5G模块",
    versionOrder: 1,
    weight: 0.9,
    weightSaving: 0,
    releaseYear: 2021,
    isCurrent: false,
    description: "早期5G通信模块",
    improvementNotes: "5G功能首次搭载",
  },
  {
    versionGroupId: "COMM_5G",
    versionCode: "V2",
    versionName: "第二代5G模块",
    versionOrder: 2,
    weight: 0.6,
    weightSaving: 0.3,
    releaseYear: 2023,
    isCurrent: true,
    description: "5G+C-V2X双模",
    improvementNotes: "集成度提升，功耗降低",
  },
  {
    versionGroupId: "COMM_BT",
    versionCode: "V1",
    versionName: "第一代蓝牙模块",
    versionOrder: 1,
    weight: 0.1,
    weightSaving: 0,
    releaseYear: 2016,
    isCurrent: false,
    description: "蓝牙4.2",
    improvementNotes: "基础蓝牙功能",
  },
  {
    versionGroupId: "COMM_BT",
    versionCode: "V2",
    versionName: "第二代蓝牙模块",
    versionOrder: 2,
    weight: 0.08,
    weightSaving: 0.02,
    releaseYear: 2018,
    isCurrent: false,
    description: "蓝牙5.0",
    improvementNotes: "性能提升",
  },
  {
    versionGroupId: "COMM_BT",
    versionCode: "V3",
    versionName: "第三代蓝牙模块",
    versionOrder: 3,
    weight: 0.07,
    weightSaving: 0.01,
    releaseYear: 2020,
    isCurrent: false,
    description: "蓝牙5.1，支持AoA定位",
    improvementNotes: "增加定位功能",
  },
  {
    versionGroupId: "COMM_BT",
    versionCode: "V4",
    versionName: "第四代蓝牙模块",
    versionOrder: 4,
    weight: 0.05,
    weightSaving: 0.02,
    releaseYear: 2022,
    isCurrent: true,
    description: "蓝牙5.2，支持手机钥匙",
    improvementNotes: "集成度提升，支持手机钥匙",
  },
  {
    versionGroupId: "COMM_WIFI",
    versionCode: "V1",
    versionName: "第一代WiFi模块",
    versionOrder: 1,
    weight: 0.12,
    weightSaving: 0,
    releaseYear: 2018,
    isCurrent: false,
    description: "WiFi 5",
    improvementNotes: "基础WiFi功能",
  },
  {
    versionGroupId: "COMM_WIFI",
    versionCode: "V2",
    versionName: "第二代WiFi模块",
    versionOrder: 2,
    weight: 0.08,
    weightSaving: 0.04,
    releaseYear: 2021,
    isCurrent: true,
    description: "WiFi 6",
    improvementNotes: "速度提升，功耗降低",
  },
  {
    versionGroupId: "BRAKE_BY_WIRE",
    versionCode: "V1",
    versionName: "第一代线控制动",
    versionOrder: 1,
    weight: 6.0,
    weightSaving: 0,
    releaseYear: 2019,
    isCurrent: false,
    description: "电子液压制动",
    improvementNotes: "早期线控制动方案",
  },
  {
    versionGroupId: "BRAKE_BY_WIRE",
    versionCode: "V2",
    versionName: "第二代线控制动",
    versionOrder: 2,
    weight: 4.5,
    weightSaving: 1.5,
    releaseYear: 2023,
    isCurrent: true,
    description: "电子液压制动，支持能量回收",
    improvementNotes: "集成度提升，重量降低",
  },
  {
    versionGroupId: "STEER_BY_WIRE",
    versionCode: "V1",
    versionName: "第一代线控转向",
    versionOrder: 1,
    weight: 5.0,
    weightSaving: 0,
    releaseYear: 2021,
    isCurrent: false,
    description: "线控转向系统",
    improvementNotes: "早期线控转向方案",
  },
  {
    versionGroupId: "STEER_BY_WIRE",
    versionCode: "V2",
    versionName: "第二代线控转向",
    versionOrder: 2,
    weight: 3.8,
    weightSaving: 1.2,
    releaseYear: 2024,
    isCurrent: true,
    description: "线控转向系统",
    improvementNotes: "冗余设计优化",
  },
  {
    versionGroupId: "ESP",
    versionCode: "V1",
    versionName: "第一代ESP",
    versionOrder: 1,
    weight: 3.5,
    weightSaving: 0,
    releaseYear: 2015,
    isCurrent: false,
    description: "ESP 8.0",
    improvementNotes: "基础车身稳定",
  },
  {
    versionGroupId: "ESP",
    versionCode: "V2",
    versionName: "第二代ESP",
    versionOrder: 2,
    weight: 3.1,
    weightSaving: 0.4,
    releaseYear: 2017,
    isCurrent: false,
    description: "ESP 9.0",
    improvementNotes: "性能优化",
  },
  {
    versionGroupId: "ESP",
    versionCode: "V3",
    versionName: "第三代ESP",
    versionOrder: 3,
    weight: 2.8,
    weightSaving: 0.3,
    releaseYear: 2019,
    isCurrent: false,
    description: "ESP 9.2",
    improvementNotes: "功能增强",
  },
  {
    versionGroupId: "ESP",
    versionCode: "V4",
    versionName: "第四代ESP",
    versionOrder: 4,
    weight: 2.2,
    weightSaving: 0.6,
    releaseYear: 2021,
    isCurrent: true,
    description: "ESP 9.3",
    improvementNotes: "集成度提升，重量降低",
  },
  {
    versionGroupId: "EPS",
    versionCode: "V1",
    versionName: "第一代EPS",
    versionOrder: 1,
    weight: 4.5,
    weightSaving: 0,
    releaseYear: 2016,
    isCurrent: false,
    description: "液压助力转向",
    improvementNotes: "基础电动助力",
  },
  {
    versionGroupId: "EPS",
    versionCode: "V2",
    versionName: "第二代EPS",
    versionOrder: 2,
    weight: 4.0,
    weightSaving: 0.5,
    releaseYear: 2019,
    isCurrent: false,
    description: "电动助力转向",
    improvementNotes: "效率提升",
  },
  {
    versionGroupId: "EPS",
    versionCode: "V3",
    versionName: "第三代EPS",
    versionOrder: 3,
    weight: 3.2,
    weightSaving: 0.8,
    releaseYear: 2022,
    isCurrent: true,
    description: "EPS电动助力转向系统",
    improvementNotes: "集成度提升，重量降低",
  },
  {
    versionGroupId: "DISPLAY_CENTER",
    versionCode: "V1",
    versionName: "第一代中控屏",
    versionOrder: 1,
    weight: 2.8,
    weightSaving: 0,
    releaseYear: 2018,
    isCurrent: false,
    description: "12.3英寸中控屏",
    improvementNotes: "早期触控屏",
  },
  {
    versionGroupId: "DISPLAY_CENTER",
    versionCode: "V2",
    versionName: "第二代中控屏",
    versionOrder: 2,
    weight: 2.3,
    weightSaving: 0.5,
    releaseYear: 2020,
    isCurrent: false,
    description: "15.6英寸中控屏",
    improvementNotes: "尺寸增大",
  },
  {
    versionGroupId: "DISPLAY_CENTER",
    versionCode: "V3",
    versionName: "第三代中控屏",
    versionOrder: 3,
    weight: 1.8,
    weightSaving: 0.5,
    releaseYear: 2023,
    isCurrent: true,
    description: "15.6英寸中控触控屏",
    improvementNotes: "轻薄化设计",
  },
  {
    versionGroupId: "DISPLAY_CLUSTER",
    versionCode: "V1",
    versionName: "第一代全液晶仪表",
    versionOrder: 1,
    weight: 1.8,
    weightSaving: 0,
    releaseYear: 2019,
    isCurrent: false,
    description: "12.3英寸液晶仪表",
    improvementNotes: "早期全液晶方案",
  },
  {
    versionGroupId: "DISPLAY_CLUSTER",
    versionCode: "V2",
    versionName: "第二代全液晶仪表",
    versionOrder: 2,
    weight: 1.2,
    weightSaving: 0.4,
    releaseYear: 2022,
    isCurrent: true,
    description: "12.3英寸全液晶仪表盘",
    improvementNotes: "集成度提升，重量降低",
  },
];

const optionPackages = [
  {
    name: "智驾包",
    code: "PKG_ADAS",
    category: "ADAS",
    description: "高阶智能驾驶辅助套装，包含感知、决策、执行全链路智驾能力",
    price: 25000,
    isPopular: true,
  },
  {
    name: "舒享包",
    code: "PKG_COMFORT",
    category: "COMFORT",
    description: "舒适享受套装，提升驾乘体验",
    price: 15000,
    isPopular: true,
  },
  {
    name: "性能包",
    code: "PKG_PERFORMANCE",
    category: "PERFORMANCE",
    description: "性能升级套装，提升操控性能",
    price: 35000,
    isPopular: false,
  },
  {
    name: "科技包",
    code: "PKG_TECH",
    category: "TECH",
    description: "科技配置套装，前沿科技体验",
    price: 18000,
    isPopular: true,
  },
  {
    name: "豪华包",
    code: "PKG_LUXURY",
    category: "LUXURY",
    description: "豪华享受套装，尊享体验",
    price: 50000,
    isPopular: false,
  },
];

const optionPackageItems = {
  PKG_ADAS: [
    { configItemId: 1, quantity: 1, isOptional: false },
    { configItemId: 2, quantity: 1, isOptional: false },
    { configItemId: 5, quantity: 2, isOptional: false },
    { configItemId: 6, quantity: 1, isOptional: false },
    { configItemId: 8, quantity: 1, isOptional: true },
    { configItemId: 9, quantity: 1, isOptional: false },
    { configItemId: 24, quantity: 1, isOptional: false },
    { configItemId: 25, quantity: 1, isOptional: true },
  ],
  PKG_COMFORT: [
    { configItemId: 11, quantity: 1, isOptional: false },
    { configItemId: 31, quantity: 1, isOptional: false },
    { configItemId: 32, quantity: 1, isOptional: false },
    { configItemId: 38, quantity: 1, isOptional: false },
    { configItemId: 28, quantity: 1, isOptional: true },
    { configItemId: 33, quantity: 1, isOptional: true },
  ],
  PKG_PERFORMANCE: [
    { configItemId: 24, quantity: 1, isOptional: false },
    { configItemId: 25, quantity: 1, isOptional: false },
    { configItemId: 28, quantity: 1, isOptional: false },
    { configItemId: 29, quantity: 1, isOptional: true },
    { configItemId: 30, quantity: 1, isOptional: true },
  ],
  PKG_TECH: [
    { configItemId: 16, quantity: 1, isOptional: false },
    { configItemId: 7, quantity: 1, isOptional: false },
    { configItemId: 8, quantity: 1, isOptional: false },
    { configItemId: 21, quantity: 1, isOptional: true },
    { configItemId: 22, quantity: 1, isOptional: true },
    { configItemId: 36, quantity: 1, isOptional: true },
  ],
  PKG_LUXURY: [
    { configItemId: 12, quantity: 1, isOptional: false },
    { configItemId: 28, quantity: 1, isOptional: false },
    { configItemId: 34, quantity: 1, isOptional: false },
    { configItemId: 35, quantity: 1, isOptional: false },
    { configItemId: 37, quantity: 1, isOptional: true },
    { configItemId: 33, quantity: 1, isOptional: true },
  ],
};

const vehicleOptionPackages = {
  "Model 3 后轮驱动版": [
    { code: "PKG_ADAS", isStandard: false },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "Model 3 长续航全轮驱动版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_TECH", isStandard: false },
  ],
  "Model Y 后轮驱动版": [
    { code: "PKG_ADAS", isStandard: false },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "Model Y 长续航全轮驱动版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "比亚迪汉EV 冠军版 506KM尊贵型": [{ code: "PKG_COMFORT", isStandard: true }],
  "比亚迪汉EV 冠军版 605KM尊荣型": [
    { code: "PKG_ADAS", isStandard: false },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_TECH", isStandard: true },
  ],
  "比亚迪汉EV 创世版 715KM旗舰型": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_LUXURY", isStandard: true },
  ],
  "比亚迪唐EV 冠军版 600KM尊享型": [
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_TECH", isStandard: false },
  ],
  "比亚迪海豹 550KM精英型": [{ code: "PKG_COMFORT", isStandard: true }],
  "比亚迪海豹 700KM尊贵型": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "小鹏G6 580长续航Max": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "小鹏G6 700四驱Max": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_PERFORMANCE", isStandard: false },
  ],
  "小鹏G9 650Max": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_LUXURY", isStandard: false },
  ],
  "小鹏X9 702Max": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_LUXURY", isStandard: false },
  ],
  "理想L7 Air": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "理想L7 Max": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_LUXURY", isStandard: true },
  ],
  "理想L8 Air": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "理想L8 Max": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_LUXURY", isStandard: true },
  ],
  "理想L9 Max": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_LUXURY", isStandard: true },
  ],
  "蔚来ET5 75kWh": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_TECH", isStandard: false },
  ],
  "蔚来ET5T 75kWh": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "蔚来ES6 75kWh": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "蔚来ES8 100kWh签名版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_LUXURY", isStandard: true },
  ],
  "问界M5 后驱智驾版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "问界M7 Max智驾版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_TECH", isStandard: true },
  ],
  "问界M9 Max智驾版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_LUXURY", isStandard: true },
  ],
  "极氪001 WE版": [
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_ADAS", isStandard: false },
  ],
  "极氪001 FR版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_PERFORMANCE", isStandard: true },
    { code: "PKG_LUXURY", isStandard: false },
  ],
  "极氪007 后驱版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "极氪X 四座版": [{ code: "PKG_COMFORT", isStandard: true }],
  "智己L7 Dynamic": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "智己LS7 Max": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_LUXURY", isStandard: true },
  ],
  "阿维塔11 鸿蒙智享升级款": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
  "阿维塔12 650四驱Max版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_TECH", isStandard: true },
  ],
  "腾势D9 DM-i 尊贵型": [
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_LUXURY", isStandard: false },
  ],
  "腾势N7 长续航性能Max版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
    { code: "PKG_PERFORMANCE", isStandard: false },
  ],
  "仰望U8 豪华版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_LUXURY", isStandard: true },
    { code: "PKG_PERFORMANCE", isStandard: true },
  ],
  "方程豹豹5 领航版": [
    { code: "PKG_ADAS", isStandard: true },
    { code: "PKG_COMFORT", isStandard: true },
  ],
};

const vehicleModels = [
  {
    name: "Model 3 后轮驱动版",
    brand: "特斯拉",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 1760,
    isNewModel: false,
  },
  {
    name: "Model 3 长续航全轮驱动版",
    brand: "特斯拉",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 1823,
    isNewModel: false,
  },
  {
    name: "Model Y 后轮驱动版",
    brand: "特斯拉",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 1929,
    isNewModel: false,
  },
  {
    name: "Model Y 长续航全轮驱动版",
    brand: "特斯拉",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 1997,
    isNewModel: false,
  },
  {
    name: "比亚迪汉EV 冠军版 506KM尊贵型",
    brand: "比亚迪",
    grade: VehicleGrade.MID,
    modelYear: 2024,
    baseWeight: 2055,
    isNewModel: true,
  },
  {
    name: "比亚迪汉EV 冠军版 605KM尊荣型",
    brand: "比亚迪",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2123,
    isNewModel: true,
  },
  {
    name: "比亚迪汉EV 创世版 715KM旗舰型",
    brand: "比亚迪",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2215,
    isNewModel: true,
  },
  {
    name: "比亚迪唐EV 冠军版 600KM尊享型",
    brand: "比亚迪",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2455,
    isNewModel: false,
  },
  {
    name: "比亚迪海豹 550KM精英型",
    brand: "比亚迪",
    grade: VehicleGrade.MID,
    modelYear: 2024,
    baseWeight: 1885,
    isNewModel: true,
  },
  {
    name: "比亚迪海豹 700KM尊贵型",
    brand: "比亚迪",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 1980,
    isNewModel: true,
  },
  {
    name: "小鹏G6 580长续航Max",
    brand: "小鹏",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 1940,
    isNewModel: true,
  },
  {
    name: "小鹏G6 700四驱Max",
    brand: "小鹏",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2090,
    isNewModel: true,
  },
  {
    name: "小鹏G9 650Max",
    brand: "小鹏",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2205,
    isNewModel: false,
  },
  {
    name: "小鹏X9 702Max",
    brand: "小鹏",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2480,
    isNewModel: true,
  },
  {
    name: "理想L7 Air",
    brand: "理想",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2405,
    isNewModel: false,
  },
  {
    name: "理想L7 Max",
    brand: "理想",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2490,
    isNewModel: false,
  },
  {
    name: "理想L8 Air",
    brand: "理想",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2470,
    isNewModel: false,
  },
  {
    name: "理想L8 Max",
    brand: "理想",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2555,
    isNewModel: false,
  },
  {
    name: "理想L9 Max",
    brand: "理想",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2690,
    isNewModel: false,
  },
  {
    name: "蔚来ET5 75kWh",
    brand: "蔚来",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2165,
    isNewModel: false,
  },
  {
    name: "蔚来ET5T 75kWh",
    brand: "蔚来",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2205,
    isNewModel: true,
  },
  {
    name: "蔚来ES6 75kWh",
    brand: "蔚来",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2230,
    isNewModel: false,
  },
  {
    name: "蔚来ES8 100kWh签名版",
    brand: "蔚来",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2510,
    isNewModel: true,
  },
  {
    name: "问界M5 后驱智驾版",
    brand: "问界",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2260,
    isNewModel: false,
  },
  {
    name: "问界M7 Max智驾版",
    brand: "问界",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2420,
    isNewModel: true,
  },
  {
    name: "问界M9 Max智驾版",
    brand: "问界",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2680,
    isNewModel: true,
  },
  {
    name: "极氪001 WE版",
    brand: "极氪",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2216,
    isNewModel: false,
  },
  {
    name: "极氪001 FR版",
    brand: "极氪",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2370,
    isNewModel: true,
  },
  {
    name: "极氪007 后驱版",
    brand: "极氪",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 1995,
    isNewModel: true,
  },
  {
    name: "极氪X 四座版",
    brand: "极氪",
    grade: VehicleGrade.MID,
    modelYear: 2024,
    baseWeight: 1845,
    isNewModel: false,
  },
  {
    name: "智己L7 Dynamic",
    brand: "智己",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2290,
    isNewModel: false,
  },
  {
    name: "智己LS7 Max",
    brand: "智己",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2545,
    isNewModel: true,
  },
  {
    name: "阿维塔11 鸿蒙智享升级款",
    brand: "阿维塔",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2310,
    isNewModel: true,
  },
  {
    name: "阿维塔12 650四驱Max版",
    brand: "阿维塔",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2280,
    isNewModel: true,
  },
  {
    name: "腾势D9 DM-i 尊贵型",
    brand: "腾势",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2615,
    isNewModel: false,
  },
  {
    name: "腾势N7 长续航性能Max版",
    brand: "腾势",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 2405,
    isNewModel: true,
  },
  {
    name: "仰望U8 豪华版",
    brand: "仰望",
    grade: VehicleGrade.LUXURY,
    modelYear: 2024,
    baseWeight: 3460,
    isNewModel: true,
  },
  {
    name: "方程豹豹5 领航版",
    brand: "方程豹",
    grade: VehicleGrade.HIGH,
    modelYear: 2024,
    baseWeight: 2800,
    isNewModel: true,
  },
];

const vehicleConfigMapping = {
  ENTRY: [1, 2, 3, 4, 6, 11, 14, 16, 18, 19, 20, 22, 24, 25, 30, 31, 37],
  MID: [1, 2, 3, 4, 6, 7, 9, 11, 14, 15, 18, 19, 20, 22, 24, 25, 30, 31, 32, 37],
  HIGH: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 14, 15, 16, 18, 19, 20, 22, 24, 25, 26, 30, 31, 32, 33, 37],
  LUXURY: [
    1, 2, 3, 4, 5, 6, 7, 8, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 24, 25, 26, 27, 28, 29,
    30, 31, 32, 33, 34, 35, 36, 37, 38,
  ],
};

const specialConfigs = {
  "仰望U8 豪华版": [28, 29],
  "极氪001 FR版": [28],
  "小鹏X9 702Max": [28],
  "理想L9 Max": [35],
  "理想L8 Max": [35],
  "问界M9 Max智驾版": [28, 35, 36],
  "腾势D9 DM-i 尊贵型": [35],
};

const infrequentlyUsedConfigs = [7, 21, 28, 29, 34, 35, 36, 38];

async function main() {
  console.log("开始清空现有数据...");
  await prisma.vehicleOptionPackage.deleteMany({});
  await prisma.optionPackageItem.deleteMany({});
  await prisma.optionPackage.deleteMany({});
  await prisma.configItemVersion.deleteMany({});
  await prisma.vehicleConfig.deleteMany({});
  await prisma.configItem.deleteMany({});
  await prisma.vehicleModel.deleteMany({});

  console.log("开始插入配置项...");
  const createdConfigItems = [];
  for (const item of configItems) {
    const created = await prisma.configItem.create({ data: item });
    createdConfigItems.push(created);
  }
  console.log(`插入配置项完成，共 ${createdConfigItems.length} 条`);

  console.log("开始插入配置项版本代次...");
  let totalVersions = 0;
  for (const version of configItemVersions) {
    const configItem = createdConfigItems.find(
      (c) => c.versionGroupId === version.versionGroupId && c.versionCode === version.versionCode
    );
    if (configItem) {
      await prisma.configItemVersion.create({
        data: {
          ...version,
          configItemId: configItem.id,
        },
      });
      totalVersions++;
    }
  }
  console.log(`插入版本代次完成，共 ${totalVersions} 条`);

  console.log("开始插入选装包...");
  const createdPackages = [];
  for (const pkg of optionPackages) {
    const created = await prisma.optionPackage.create({ data: pkg });
    createdPackages.push(created);
  }
  console.log(`插入选装包完成，共 ${createdPackages.length} 个`);

  console.log("开始插入选装包配置项...");
  let totalPackageItems = 0;
  for (const pkg of createdPackages) {
    const items = optionPackageItems[pkg.code] || [];
    for (const item of items) {
      try {
        await prisma.optionPackageItem.create({
          data: {
            optionPackageId: pkg.id,
            configItemId: item.configItemId,
            quantity: item.quantity,
            isOptional: item.isOptional,
          },
        });
        totalPackageItems++;
      } catch (e) {
        console.log(`跳过选装包配置: ${pkg.code}, 配置${item.configItemId}`);
      }
    }
  }
  console.log(`插入选装包配置项完成，共 ${totalPackageItems} 条`);

  console.log("开始插入车型...");
  const createdVehicles = [];
  for (const vehicle of vehicleModels) {
    const created = await prisma.vehicleModel.create({ data: vehicle });
    createdVehicles.push(created);
  }
  console.log(`插入车型完成，共 ${createdVehicles.length} 款`);

  console.log("开始插入搭载关系...");
  let totalConfigs = 0;
  for (const vehicle of createdVehicles) {
    const baseConfigs = vehicleConfigMapping[vehicle.grade] || [];
    const specialConfigIds = specialConfigs[vehicle.name] || [];
    const allConfigIds = [...new Set([...baseConfigs, ...specialConfigIds])];

    for (const configId of allConfigIds) {
      const isFrequentlyUsed = !infrequentlyUsedConfigs.includes(configId);
      try {
        await prisma.vehicleConfig.create({
          data: {
            vehicleModelId: vehicle.id,
            configItemId: configId,
            quantity: [3, 4].includes(configId) ? (configId === 3 ? 4 : 12) : 1,
            isFrequentlyUsed,
            adoptionDate: new Date("2023-01-01"),
          },
        });
        totalConfigs++;
      } catch (e) {
        console.log(`跳过重复配置: 车型${vehicle.id}, 配置${configId}`);
      }
    }
  }
  console.log(`插入搭载关系完成，共 ${totalConfigs} 条`);

  console.log("开始插入车型选装包关联...");
  let totalVehiclePackages = 0;
  for (const vehicle of createdVehicles) {
    const pkgList = vehicleOptionPackages[vehicle.name] || [];
    for (const pkgInfo of pkgList) {
      const pkg = createdPackages.find((p) => p.code === pkgInfo.code);
      if (pkg) {
        try {
          await prisma.vehicleOptionPackage.create({
            data: {
              vehicleModelId: vehicle.id,
              optionPackageId: pkg.id,
              isStandard: pkgInfo.isStandard,
              adoptionDate: new Date("2023-01-01"),
            },
          });
          totalVehiclePackages++;
        } catch (e) {
          console.log(`跳过车型选装包: ${vehicle.name}, ${pkgInfo.code}`);
        }
      }
    }
  }
  console.log(`插入车型选装包关联完成，共 ${totalVehiclePackages} 条`);

  console.log("\n=== 数据统计 ===");
  const totalWeight = configItems.reduce((sum, item) => sum + item.typicalWeight, 0);
  console.log(`配置项总重量: ${totalWeight.toFixed(1)} kg`);

  const categoryWeights = {};
  configItems.forEach((item) => {
    categoryWeights[item.category] = (categoryWeights[item.category] || 0) + item.typicalWeight;
  });
  console.log("\n各类别重量分布:");
  Object.entries(categoryWeights).forEach(([cat, weight]) => {
    console.log(
      `  ${cat}: ${weight.toFixed(1)} kg (${((weight / totalWeight) * 100).toFixed(1)}%)`
    );
  });

  const totalVersionSaving = configItemVersions.reduce((sum, v) => sum + v.weightSaving, 0);
  console.log(`\n版本代次累计减重: ${totalVersionSaving.toFixed(1)} kg`);

  console.log("\n选装包统计:");
  for (const pkg of createdPackages) {
    const items = optionPackageItems[pkg.code] || [];
    const pkgWeight = items.reduce((sum, item) => {
      const config = createdConfigItems.find((c) => c.id === item.configItemId);
      return sum + (config ? config.typicalWeight * item.quantity : 0);
    }, 0);
    console.log(`  ${pkg.name}: ${items.length}项配置, 增重${pkgWeight.toFixed(1)}kg`);
  }

  console.log("\n数据种子执行完成!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
